# we tell travis that sudo is required (for docker)
sudo: required
#Travis will install a copy of docker into our running container
services:
  - docker

# series of steps before we attempt to test our app or deploy
before_install:
  - docker build -t rubenberna/docker-reactApp -f Dockerfile.dev .

# we add the -- --coverage command just to make sure the npm test suit is exited after it ran, because the default behaviour is to expect an input
script:
  - docker run -e CI=true rubenberna/docker-reactApp yarn test -- --coverage